---
config:
  layout: elk
  theme: redux
  look: neo
---
flowchart LR
 subgraph ODS["Operational Data Sources"]
    direction LR
        ExtAPIs["External APIs"]
        SourceDBs[("Operational<br>Databases")]
        AppsServices["Apps & Services"]
  end
 subgraph MB["Message Bus"]
        MessageBus["Topics"]
        SchemaRegistry["Schema Registry"]
  end
 subgraph IngestionLayer["Ingestion Layer"]
    direction LR
        BatchIngestTools["Data Ingestion Tools"]
        StreamIngestTools["Data Ingestion Tools"]
        MB
  end
 subgraph TransformationLayer["Transformation Layer"]
    direction LR
        BronzeLayer[("Bronze Layer")]
        SilverLayer[("Silver Layer")]
        GoldLayer[("Gold Layer")]
        UserSpace[("User Space")]
        BatchProcessing["Batch Processing Tools"]
        Orchestration["Orchestration Tools"]
        StreamProcessing["Stream Processing Tools"]
        DataQuality["Data Quality Tools"]
  end
 subgraph SystemsServingLayer["Systems Serving Layer"]
    direction LR
        QueryFederation["Query Federation<br>Tools"]
        SpecializedDatabases["Specialized<br>Databases"]
        Aggregations[("Aggregations<br>&amp; Views")]
        Metrics[("Metrics<br>&amp; KPIs")]
  end
 subgraph UserServingLayer["User Serving Layer"]
    direction LR
        Dashboarding["Dashboarding Tools"]
        CacheEngines[("Cache Engines")]
        ReportingTools["Reporting Tools"]
  end
 subgraph GovernanceLayer["Governance Layer"]
    direction LR
        DataCatalog["Data Catalog"]
        DataLineage["Data Lineage"]
        RBAC["RBAC"]
        DataDiscovery["Data Discovery"]
  end
 subgraph DLH["Data Lakehouse"]
    direction LR
        IngestionLayer
        TransformationLayer
        SystemsServingLayer
        UserServingLayer
        GovernanceLayer
  end
    ExtAPIs -- 3 --> BatchIngestTools
    SourceDBs -- 1 --> BatchIngestTools
    StreamIngestTools -- 7 --> BronzeLayer
    AppsServices --> SourceDBs
    BronzeLayer -.-> SilverLayer
    SilverLayer -.-> GoldLayer
    StreamProcessing ~~~ BatchProcessing
    BatchProcessing ~~~ Orchestration
    DataCatalog ~~~ DataLineage
    DataLineage ~~~ RBAC
    ReportingTools ~~~ Dashboarding
    DataDiscovery ~~~ DataCatalog
    Orchestration ~~~ DataQuality
    GoldLayer ~~~ UserSpace
    BatchIngestTools -- 4 --> MB
    AppsServices -- 2 --> MB
    MB -- 5 --> StreamIngestTools
    MB <-- 6 --> StreamProcessing
    TransformationLayer -- 8 --> SystemsServingLayer
    SystemsServingLayer -- 9 --> UserServingLayer
    SystemsServingLayer -- 10 --> AppsServices
    Aggregations ~~~ Metrics
    SpecializedDatabases ~~~ QueryFederation

    MessageBus@{ shape: h-cyl}
    SpecializedDatabases@{ shape: rect}
    classDef default stroke:#000000,stroke-width:1px,color:#000000
    style IngestionLayer fill:#FFF9C4,stroke:#FFD600,stroke-width:2px
    style TransformationLayer fill:#FFCDD2,stroke:#D50000,stroke-width:2px
    style SystemsServingLayer fill:#C7E9FB,stroke:#0288D1,stroke-width:2px
    style UserServingLayer fill:#E1BEE7,stroke:#AA00FF,stroke-width:2px
    style GovernanceLayer fill:#C8E6C9,stroke:#00C853,stroke-width:2px
    style ODS stroke:#000000,fill:#BDBCCC,stroke-width:1px
    style DLH stroke:#000000,fill:#e6e6e6,stroke-width:2px